-- ============================================================================
-- PROJECT: HOSPITAL PATIENT RECORD SYSTEM (ORACLE COE PROJECT)
-- SCRIPT: 01_schema_ddl.sql
-- PURPOSE: Table creation, primary keys, foreign keys, and integrity constraints
-- TARGET: Oracle Database 12c/18c/19c/21c/23c & Oracle Live SQL
-- ============================================================================

-- Clean up existing tables in reverse dependency order
BEGIN
    FOR t IN (
        SELECT table_name FROM user_tables 
        WHERE table_name IN ('PRESCRIPTION', 'BILL', 'MEDICAL_RECORD', 'APPOINTMENT', 'DOCTOR', 'PATIENT', 'DEPARTMENT')
    ) LOOP
        EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS';
    END LOOP;
END;
/

-- ----------------------------------------------------------------------------
-- 1. DEPARTMENT TABLE
-- Purpose: Stores hospital department details
-- ----------------------------------------------------------------------------
CREATE TABLE DEPARTMENT (
    department_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_name VARCHAR2(50) NOT NULL UNIQUE,
    location        VARCHAR2(100) NOT NULL
);

-- ----------------------------------------------------------------------------
-- 2. DOCTOR TABLE
-- Purpose: Stores doctor profile and department assignment
-- ----------------------------------------------------------------------------
CREATE TABLE DOCTOR (
    doctor_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doctor_name     VARCHAR2(100) NOT NULL,
    specialization  VARCHAR2(100) NOT NULL,
    phone           VARCHAR2(15) NOT NULL,
    email           VARCHAR2(100) NOT NULL UNIQUE,
    department_id   NUMBER NOT NULL,
    CONSTRAINT fk_doc_dept FOREIGN KEY (department_id) 
        REFERENCES DEPARTMENT(department_id)
);

-- ----------------------------------------------------------------------------
-- 3. PATIENT TABLE
-- Purpose: Stores basic patient demographics, medical identifiers, and contact info
-- ----------------------------------------------------------------------------
CREATE TABLE PATIENT (
    patient_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_name    VARCHAR2(100) NOT NULL,
    date_of_birth   DATE NOT NULL,
    gender          VARCHAR2(10) NOT NULL,
    phone           VARCHAR2(15) NOT NULL,
    email           VARCHAR2(100) NOT NULL UNIQUE,
    address         VARCHAR2(255) NOT NULL,
    blood_group     VARCHAR2(5) NOT NULL,
    created_at      DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT chk_patient_gender CHECK (gender IN ('MALE', 'FEMALE', 'OTHER')),
    CONSTRAINT chk_patient_blood CHECK (blood_group IN ('A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-'))
);

-- ----------------------------------------------------------------------------
-- 4. APPOINTMENT TABLE
-- Purpose: Stores appointments between patients and doctors
-- ----------------------------------------------------------------------------
CREATE TABLE APPOINTMENT (
    appointment_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id       NUMBER NOT NULL,
    doctor_id        NUMBER NOT NULL,
    appointment_date DATE NOT NULL,
    appointment_time VARCHAR2(10) NOT NULL,
    reason           VARCHAR2(255) NOT NULL,
    status           VARCHAR2(20) DEFAULT 'SCHEDULED' NOT NULL,
    CONSTRAINT fk_appt_patient FOREIGN KEY (patient_id) 
        REFERENCES PATIENT(patient_id),
    CONSTRAINT fk_appt_doctor FOREIGN KEY (doctor_id) 
        REFERENCES DOCTOR(doctor_id),
    CONSTRAINT chk_appt_status CHECK (status IN ('SCHEDULED', 'COMPLETED', 'CANCELLED'))
);

-- ----------------------------------------------------------------------------
-- 5. MEDICAL_RECORD TABLE
-- Purpose: Stores clinical diagnosis, treatment details, and visit notes
-- ----------------------------------------------------------------------------
CREATE TABLE MEDICAL_RECORD (
    record_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id      NUMBER NOT NULL,
    doctor_id       NUMBER NOT NULL,
    appointment_id  NUMBER,
    diagnosis       VARCHAR2(255) NOT NULL,
    treatment       VARCHAR2(255) NOT NULL,
    record_date     DATE DEFAULT SYSDATE NOT NULL,
    notes           VARCHAR2(500),
    CONSTRAINT fk_mr_patient FOREIGN KEY (patient_id) 
        REFERENCES PATIENT(patient_id),
    CONSTRAINT fk_mr_doctor FOREIGN KEY (doctor_id) 
        REFERENCES DOCTOR(doctor_id),
    CONSTRAINT fk_mr_appointment FOREIGN KEY (appointment_id) 
        REFERENCES APPOINTMENT(appointment_id)
);

-- ----------------------------------------------------------------------------
-- 6. PRESCRIPTION TABLE
-- Purpose: Stores medications prescribed for each medical record
-- ----------------------------------------------------------------------------
CREATE TABLE PRESCRIPTION (
    prescription_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    record_id       NUMBER NOT NULL,
    medicine_name   VARCHAR2(100) NOT NULL,
    dosage          VARCHAR2(50) NOT NULL,
    frequency       VARCHAR2(50) NOT NULL,
    duration_days   NUMBER(3) NOT NULL,
    CONSTRAINT fk_presc_record FOREIGN KEY (record_id) 
        REFERENCES MEDICAL_RECORD(record_id),
    CONSTRAINT chk_presc_duration CHECK (duration_days > 0)
);

-- ----------------------------------------------------------------------------
-- 7. BILL TABLE
-- Purpose: Stores billing, fee breakdowns, and payment status for visits
-- ----------------------------------------------------------------------------
CREATE TABLE BILL (
    bill_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id       NUMBER NOT NULL,
    appointment_id   NUMBER,
    bill_date        DATE DEFAULT SYSDATE NOT NULL,
    consultation_fee NUMBER(10,2) DEFAULT 0.00 NOT NULL,
    medicine_fee     NUMBER(10,2) DEFAULT 0.00 NOT NULL,
    total_amount     NUMBER(10,2) NOT NULL,
    payment_status   VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
    CONSTRAINT fk_bill_patient FOREIGN KEY (patient_id) 
        REFERENCES PATIENT(patient_id),
    CONSTRAINT fk_bill_appointment FOREIGN KEY (appointment_id) 
        REFERENCES APPOINTMENT(appointment_id),
    CONSTRAINT chk_bill_consult_fee CHECK (consultation_fee >= 0),
    CONSTRAINT chk_bill_med_fee CHECK (medicine_fee >= 0),
    CONSTRAINT chk_bill_total CHECK (total_amount >= 0),
    CONSTRAINT chk_bill_status CHECK (payment_status IN ('PAID', 'PENDING'))
);
